name: Deploy to heroku

# mainブランチにpushされた時に実行
on:
  push:
    branches:
      - main

# 実行されるジョブ
jobs:
  deploy:
    # テスト環境を最新バージョンのUbuntu(Linux)に設定
    runs-on: ubuntu-latest

    steps:
      # リポジトリのコードをチェックアウト
      # ワークフローがリポジトリのコードにアクセスできる
      - uses: actions/checkout@v4

      - name: Login to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:login

      - name: Build and push
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          docker build -t registry.heroku.com/sakura-thanks-bec5c810b25a/web .
          docker push registry.heroku.com/sakura-thanks-bec5c810b25a/web

      - name: Release
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku container:release web -a sakura-thanks-bec5c810b25a

      - name: Database migration
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: heroku run rails db:migrate -a sakura-thanks-bec5c810b25a